### ISSUE TITLE
Enable record timestamp for attributes

### ISSUE THREAD

**Issue by Lab41PaulM** [v5analytics/vertexium#8]
If I am not mistaken, the API currently does not support developer specified timestamps for attributes? If not supported, any plans to do so soon?

For example, if I wanted to keep track of the outdoor temperature of an area on a daily basis, I might treat the place as a vertex and the temperature as an attribute of that vertex.  For each temperature reading, I would want to use the timestamp reflecting when that temperature was taken.

**Comment by joeferner** [comment]
Recording and storing timestamps should be trivial. Retrieving them is a little more difficult.

The first problem is with querying, Vertexium uses Elasticsearch for non-id based queries. Currently Elasticsearch has no concept of timestamps. So having a query such as, give me the temperatures between 30 and 40 in December would be challenging.

The second problem is how Vertexium retrieves elements. Currently when you ask for an element Vertexium will retrieve the element along with all the properties. The API would need to change to support fetching a time range of properties.

With all that being said, the Vertexium team is looking into how we would pull all this off since we have a desire to implement these exact features for our product.

**Comment by Lab41PaulM** [comment]
This would be a great enhancement. Thanks for the quick response.

**Comment by joeferner** [comment]
The latest API now supports saving and retrieving time-stamped data (Accumulo).  At this time there is no support to query (ElasticSearch) for old values.

**Comment by Lab41PaulM** [comment]
Awesome! Thanks Joe. Will start playing with it today. Will let you know if I come across any other issues.
